language: generic
sudo: false
branches:
  only:
  - gh-pages
addons:
  hosts:
    - develop.spacemacs.org
services:
  - docker
install:
  - docker pull jare/linkchecker
  - docker pull taka0225/alpine-http-server
script: ./travis/travis.sh
